AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sample-sam-app

  Sample SAM Template for sample-sam-app

Globals:
  Function:
    Timeout: 15

Resources:
  CheckHeaderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: check/
      Handler: index.checkHeader
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        CheckHeader:
          Type: Api
          Properties:
            Path: /check-header
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - src/index.ts

Outputs:
  CheckHeaderApi:
    Description: "API Gateway endpoint URL for Prod stage for Check Header function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/check-header/"
  CheckHeaderFunction:
    Description: "Check Header Lambda Function ARN"
    Value: !GetAtt CheckHeaderFunction.Arn
  CheckHeaderFunctionIamRole:
    Description: "Implicit IAM Role created for Check Header function"
    Value: !GetAtt CheckHeaderFunctionRole.Arn
